-- Disable RLS for local development (makes testing easier)
-- In production, you would want proper RLS policies

ALTER TABLE IF EXISTS positions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS game_players DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS games DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS equity_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_executions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS price_data DISABLE ROW LEVEL SECURITY;
